info:
  contact: {}
paths:
  /article/{id}:
    get:
      consumes:
      - application/json
      description: Get Article by ID
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get Article by ID
      tags:
      - article
  /create:
    post:
      consumes:
      - application/json
      description: Create a new user
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Create a new user
      tags:
      - user
swagger: "2.0"
